version: '3'

services:
  redis:
    container_name: "redis"
    image: "redis:alpine"

  postgres:
    container_name: "postgres"
    build: ./docker/postgres
    volumes:
        - ./docker/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_MULTIPLE_DATABASES: serverdev,servertest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass

  nginx:
    container_name: "nginx"
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart:
      always
    ports:
      - 80:80
    depends_on:
      - server
      - website

  server:
    container_name: "server"
    build:
      context: ./services/server
      dockerfile: Dockerfile
    ports:
      - "10020:10020"
      - "9229:9229"
    volumes:
      - ./services/server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis
      - postgres
    command: ['yarn', 'start']

  website:
    container_name: "website"
    build:
      context: ./services/website
      dockerfile: Dockerfile
    ports:
      - "10060:10060"
    volumes:
      - ./services/website:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true    # for bug in react-scripts 3.4.1
    depends_on:
      - redis
      - postgres
    environment:
      PORT: "10060"
      CHOKIDAR_USEPOLLING: 'true'
    command: ['yarn', 'start']
